name: Feature Request
description: Request a feature
title: "[REQUEST]: "
labels: 'State: unverified, Type: request'
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    id: what-request
    attributes:
      label: What would you like to request?
      description: Tell us, what you would like to request!
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Release
      description: Which release would fit to this feature?
      options:
        - v1.0
        - v1.1
        - Future releases
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why?
      description: Tell us, why you think, this would be a nice or fitting feature for JET
  - type: checkboxes
    id: terms
    attributes:
      label: Check & Safe
      description: By submitting this request, you agree to have checked the different individual things below
      options:
        - label: I agree to have checked, that this is no duplicated request
          required: true


